# 파이토치 기본 패키지 구성
1. torch
  - 메인 네임스페이스. 텐서등의 다양한 수학 함수가 포함. Numpy와 유사
2. torch.autograd
  - 자동 미분을 위한 함수들 포함. 자동 미분의 on/off를 제어하는 콘텍스트 매니저(enable_grad/no_grad)나 자체 미분 함수를 정의할 때 사용하는 'Function'등이 포함.
3. torch.nn
  - 신경망을 구축하기 위한 다양한 데이터 구조나 레이어가 정의되어 있음.
4. torch.optim
  - 확률적 경사 하강법(Stochastic Gradient Descent, SGD)를 중심으로 한 파라미터 최적화 알고리즘이 구현되어 있다.
5. torch.utils.data
  - SGD연산을 반복할 때 사용하는 미니 배치용 유틸리티 함수가 포함되어 있음.
6. torch.onnx
  - ONNX(Open Neural Network Exchange)의 포맷으로 모델을 export할 때 사용. ONNX는 서로 다른 딥러닝 프레임워크 간에 모델을 공유할 때 사용.

# 텐서 조작하기

In [32]:
import torch
import numpy as np

In [33]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [34]:
print(t.dim())
print(t.size())
print(t.shape)

1
torch.Size([7])
torch.Size([7])


In [35]:
print(t[0])

tensor(0.)


## 행렬 곱셈과 곱셈의 차이(Matrix Multiplication vs Multiplication)

In [36]:
#Matrix Multiplication

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [37]:
#Element-wise Multiplication (BroadCasting)

m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


## 각종 연산

In [38]:
# mean

t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [39]:
# dim = 0 or 1

t = torch.FloatTensor([[1, 2], [3, 4]])
print(t.mean())
print(t.mean(dim=0)) # dim = 0 : 첫번째 차원(row)을 제거하고 mean 수행
print(t.mean(dim=1)) # dim = 1 : 두번째 차원(column)을 제거하고 mean 수행
print(t.mean(dim=-1)) # dim = -1 : 마지막 차원(column)을 제거하고 mean 수행

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [40]:
# max & argmax

t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

print(t.max()) # Returns one value: max
print('\n')
print(t.max(dim=0)) # Returns two values: max and argmax

tensor([[1., 2.],
        [3., 4.]])
tensor(4.)


torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


## View
- 원소의 수를 유지하면서 텐서의 크기 변경. 매우 중요!
- np.reshape와 유사

In [41]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

print(ft.shape)

torch.Size([2, 2, 3])


In [42]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [43]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze
- 1인 차원을 제거

In [44]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)


tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [45]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


## Unsqueeze
- 특정 위치에 차원을 1추가

In [46]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [47]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)
print('\n')
print(ft.unsqueeze(-1)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(-1).shape)


tensor([[0., 1., 2.]])
torch.Size([1, 3])


tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Type Casting
- tensor의 자료형을 반환하는 것

In [48]:
lt = torch.LongTensor([1, 2, 3, 4]) # long type tensor
print(lt)

tensor([1, 2, 3, 4])


In [49]:
print(lt.float()) # long to float type tensor

tensor([1., 2., 3., 4.])


In [50]:
bt = torch.ByteTensor([True, False, False, True]) # byte type tensor
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [51]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## concatenate
- 연결하기

In [52]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [54]:
print(torch.cat([x, y], dim=0)) # dim = 0 : 첫번째 차원을 늘리기
print(torch.cat([x, y], dim=1)) # dim = 1 : 두번째 차원을 늘리기

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## stacking
- stacking은 concat보다 많은 연산을 포함

In [55]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [56]:
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


# Linear Regression
- Goal : loss/cost function을 최소화하여 데이터를 가장 잘 설명할 수 있는 linear equation을 찾아내는 것
  - Optimizing : SGD방식을 이용해서 Weight를 update. W = W - lr*W

In [65]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [66]:
# 현재 실습하고 있는 파이썬 코드를 재실행해도 다음에도 같은 결과가 나오도록 랜덤 시드(random seed)를 줍니다.
torch.manual_seed(1)

In [70]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [72]:
# 가중치 W를 0으로 초기화하고 학습을 통해 값이 변경되는 변수임을 명시함.
W = torch.zeros(1, requires_grad=True) 
# 가중치 W를 출력
print(W)

tensor([0.], requires_grad=True)


In [74]:
b = torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [75]:
hypothesis = x_train * W + b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [76]:
# 앞서 배운 torch.mean으로 평균을 구한다.
cost = torch.mean((hypothesis - y_train) ** 2) # mse
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [77]:
optimizer = optim.SGD([W, b], lr=0.01)

In [78]:
# gradient를 0으로 초기화
optimizer.zero_grad() 
# 비용 함수를 미분하여 gradient 계산
cost.backward() 
# W와 b를 업데이트
optimizer.step() 

## 전체 코드

In [79]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])
# 모델 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=0.01)

nb_epochs = 1999 # 원하는만큼 경사 하강법을 반복
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    hypothesis = x_train * W + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, nb_epochs, W.item(), b.item(), cost.item()
        ))

Epoch    0/1999 W: 0.187, b: 0.080 Cost: 18.666666
Epoch  100/1999 W: 1.746, b: 0.578 Cost: 0.048171
Epoch  200/1999 W: 1.800, b: 0.454 Cost: 0.029767
Epoch  300/1999 W: 1.843, b: 0.357 Cost: 0.018394
Epoch  400/1999 W: 1.876, b: 0.281 Cost: 0.011366
Epoch  500/1999 W: 1.903, b: 0.221 Cost: 0.007024
Epoch  600/1999 W: 1.924, b: 0.174 Cost: 0.004340
Epoch  700/1999 W: 1.940, b: 0.136 Cost: 0.002682
Epoch  800/1999 W: 1.953, b: 0.107 Cost: 0.001657
Epoch  900/1999 W: 1.963, b: 0.084 Cost: 0.001024
Epoch 1000/1999 W: 1.971, b: 0.066 Cost: 0.000633
Epoch 1100/1999 W: 1.977, b: 0.052 Cost: 0.000391
Epoch 1200/1999 W: 1.982, b: 0.041 Cost: 0.000242
Epoch 1300/1999 W: 1.986, b: 0.032 Cost: 0.000149
Epoch 1400/1999 W: 1.989, b: 0.025 Cost: 0.000092
Epoch 1500/1999 W: 1.991, b: 0.020 Cost: 0.000057
Epoch 1600/1999 W: 1.993, b: 0.016 Cost: 0.000035
Epoch 1700/1999 W: 1.995, b: 0.012 Cost: 0.000022
Epoch 1800/1999 W: 1.996, b: 0.010 Cost: 0.000013
Epoch 1900/1999 W: 1.997, b: 0.008 Cost: 0.000008

## 자동미분(Autograd)

In [80]:
w = torch.tensor(2.0, requires_grad=True)

In [81]:
y = w**2
z = 2*y + 5

In [82]:
z.backward()

In [83]:
print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 8.0


## 다중 선형 회귀(Multiple Linear Regression)

In [86]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  80], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

# 모델 초기화
W = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([W, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):

    # H(x) 계산
    # 편향 b는 브로드 캐스팅되어 각 샘플에 더해집니다.
    hypothesis = x_train.matmul(W) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch    2/20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7861,  95.8280]) Cost: 3069.590820
Epoch    3/20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670288
Epoch    4/20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.481873
Epoch    5/20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch    6/20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch    7/20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch    8/20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch    9/20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch   10/20 hyp

## nn.Module 활용

In [87]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [88]:
# 모델을 선언 및 초기화. 단순 선형 회귀이므로 input_dim=1, output_dim=1.
model = nn.Linear(1,1)

In [89]:
print(list(model.parameters())) # requires_grad = True로 자동설정됨

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [90]:
# optimizer 설정. 경사 하강법 SGD를 사용하고 learning rate를 의미하는 lr은 0.01
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

In [91]:
# 전체 훈련 데이터에 대해 경사 하강법을 2,000회 반복
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


- 입력된 x값으로 부터 y 값을 예측하는 것을 forward 연산이라고 함.
  - 학습 과정에서, prediction = model(x_train) : forward 연산
  - 학습 후에, pred_y = model(new_var) : forward 연산
  - cost.backward() : backward 연산

### nn.Module, 다중 선형회귀

In [93]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75], # 5x3
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]]) # 5x1

In [94]:
# 모델을 선언 및 초기화. 다중 선형 회귀이므로 input_dim=3, output_dim=1.
model = nn.Linear(3,1)

In [95]:
print(list(model.parameters()))

[Parameter containing:
tensor([[-0.1119,  0.2710, -0.5435]], requires_grad=True), Parameter containing:
tensor([0.3462], requires_grad=True)]


In [96]:
optimizer = optim.SGD(model.parameters(), lr = 1e-5)

In [97]:
for i in range(2000) : 

  # H(x) 계산
  prediction = model(x_train) # == model.forward(x_train)

  # cost
  cost = F.mse_loss(prediction, y_train)

  #backward
  optimizer.zero_grad() # 초기화
  cost.backward() # 미분
  optimizer.step() # 파라미터 업데이트

  if (i+1)%100 == 0 : 
    # 100번마다 로그 출력
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        i+1, 2000, cost.item()
    ))

Epoch  100/2000 Cost: 5.963196
Epoch  200/2000 Cost: 5.657667
Epoch  300/2000 Cost: 5.368217
Epoch  400/2000 Cost: 5.094056
Epoch  500/2000 Cost: 4.834363
Epoch  600/2000 Cost: 4.588363
Epoch  700/2000 Cost: 4.355329
Epoch  800/2000 Cost: 4.134592
Epoch  900/2000 Cost: 3.925489
Epoch 1000/2000 Cost: 3.727418
Epoch 1100/2000 Cost: 3.539782
Epoch 1200/2000 Cost: 3.362067
Epoch 1300/2000 Cost: 3.193709
Epoch 1400/2000 Cost: 3.034220
Epoch 1500/2000 Cost: 2.883162
Epoch 1600/2000 Cost: 2.740072
Epoch 1700/2000 Cost: 2.604525
Epoch 1800/2000 Cost: 2.476128
Epoch 1900/2000 Cost: 2.354475
Epoch 2000/2000 Cost: 2.239239


In [99]:
# validation

# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 
print(list(model.parameters()))

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[153.7189]], grad_fn=<AddmmBackward0>)
[Parameter containing:
tensor([[0.8540, 0.8475, 0.3096]], requires_grad=True), Parameter containing:
tensor([0.3568], requires_grad=True)]


## Class로 Pytorch 모델 구현하기

In [122]:
model = nn.Linear(1,1)

# 이를 class로 구현하면,

class LinearRegressionModel(nn.Module): # nn.Module을 상속받음
  def __init__(self) :
    super().__init__() # parent Class의 __init__을 그대로 상속받아 사용
    self.linear = nn.Linear(1,1)

  def forward(self, x) : # 학습 데이터를 받아와 forward 연산을 진행시키는 함수 / model 객체를 생성하면 자동으로 실행됨
    return self.linear(x)

model = LinearRegressionModel()

### 직접 class를 활용해 구현해보기

In [108]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [119]:
class LinearRegressionModel(nn.Module): # nn.Module을 상속받음
  def __init__(self) :
    super().__init__() # parent Class의 __init__을 그대로 상속받아 사용
    self.linear = nn.Linear(1,1)

  def forward(self, x) : # 학습 데이터를 받아와 forward 연산을 진행시키는 함수 / model 객체를 생성하면 자동으로 실행됨
    return self.linear(x)

In [120]:
model = LinearRegressionModel()
optimizer = optim.SGD(model.parameters(), lr = 1e-2)

In [121]:
num_epochs = 2000
for epoch in range(num_epochs+1) :

  prediction = model(x_train)

  cost = F.mse_loss(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))


Epoch    0/2000 Cost: 24.685446
Epoch  100/2000 Cost: 0.071069
Epoch  200/2000 Cost: 0.043916
Epoch  300/2000 Cost: 0.027138
Epoch  400/2000 Cost: 0.016769
Epoch  500/2000 Cost: 0.010362
Epoch  600/2000 Cost: 0.006403
Epoch  700/2000 Cost: 0.003957
Epoch  800/2000 Cost: 0.002445
Epoch  900/2000 Cost: 0.001511
Epoch 1000/2000 Cost: 0.000934
Epoch 1100/2000 Cost: 0.000577
Epoch 1200/2000 Cost: 0.000357
Epoch 1300/2000 Cost: 0.000220
Epoch 1400/2000 Cost: 0.000136
Epoch 1500/2000 Cost: 0.000084
Epoch 1600/2000 Cost: 0.000052
Epoch 1700/2000 Cost: 0.000032
Epoch 1800/2000 Cost: 0.000020
Epoch 1900/2000 Cost: 0.000012
Epoch 2000/2000 Cost: 0.000008


## 미니배치와 데이터 로드(Mini Batch and Data Load)

In [123]:
from torch.utils.data import Dataset, TensorDataset,DataLoader

In [124]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [125]:
dataset = TensorDataset(x_train, y_train)

In [128]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=True)
# shuffle = True : epoch마다 batch의 순서를 바꿔서 학습

In [129]:
model = nn.Linear(3,1)
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5) 

In [130]:
num_epochs = 20
for epoch in range(num_epochs+1) : 
  for batch_idx, samples in enumerate(dataloader) : 
    x_train, y_train = samples

    #forward
    prediction = model(x_train)

    #cost
    cost = F.mse_loss(prediction, y_train)

    #backward
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    #print
    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, num_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 6111.545898
Epoch    0/20 Batch 2/3 Cost: 2102.446045
Epoch    0/20 Batch 3/3 Cost: 653.481995
Epoch    1/20 Batch 1/3 Cost: 207.813858
Epoch    1/20 Batch 2/3 Cost: 75.565811
Epoch    1/20 Batch 3/3 Cost: 1.367718
Epoch    2/20 Batch 1/3 Cost: 18.087572
Epoch    2/20 Batch 2/3 Cost: 0.384828
Epoch    2/20 Batch 3/3 Cost: 20.991934
Epoch    3/20 Batch 1/3 Cost: 3.663338
Epoch    3/20 Batch 2/3 Cost: 6.350983
Epoch    3/20 Batch 3/3 Cost: 5.858238
Epoch    4/20 Batch 1/3 Cost: 4.272526
Epoch    4/20 Batch 2/3 Cost: 6.911891
Epoch    4/20 Batch 3/3 Cost: 4.882916
Epoch    5/20 Batch 1/3 Cost: 1.244126
Epoch    5/20 Batch 2/3 Cost: 9.133160
Epoch    5/20 Batch 3/3 Cost: 7.230614
Epoch    6/20 Batch 1/3 Cost: 6.731429
Epoch    6/20 Batch 2/3 Cost: 3.294933
Epoch    6/20 Batch 3/3 Cost: 6.469173
Epoch    7/20 Batch 1/3 Cost: 7.275612
Epoch    7/20 Batch 2/3 Cost: 3.370646
Epoch    7/20 Batch 3/3 Cost: 9.402941
Epoch    8/20 Batch 1/3 Cost: 3.832781
Epoch    8/2

In [131]:
# valdation

# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[153.9086]], grad_fn=<AddmmBackward0>)


## Custom Dataset

```
# 코드로 형식 지정됨
class CustomDataset(torch.utils.data.Dataset): 
  def __init__(self):
  데이터셋의 전처리를 해주는 부분

  def __len__(self):
  데이터셋의 길이. 즉, 총 샘플의 수를 적어주는 부분

  def __getitem__(self, idx): 
  데이터셋에서 특정 1개의 샘플을 가져오는 함수
```

In [132]:
# Dataset 상속
class CustomDataset(Dataset): 
  def __init__(self):
    self.x_data = [[73, 80, 75],
                   [93, 88, 93],
                   [89, 91, 90],
                   [96, 98, 100],
                   [73, 66, 70]]
    self.y_data = [[152], [185], [180], [196], [142]]

  # 총 데이터의 개수를 리턴
  def __len__(self): 
    return len(self.x_data)

  # 인덱스를 입력받아 그에 맵핑되는 입출력 데이터를 파이토치의 Tensor 형태로 리턴
  def __getitem__(self, idx): 
    x = torch.FloatTensor(self.x_data[idx])
    y = torch.FloatTensor(self.y_data[idx])
    return x, y

In [134]:
dataset = CustomDataset()
dataloader = DataLoader(dataset, batch_size = 2, shuffle = True)

In [135]:
model = nn.Linear(3,1)
optimizer = optim.SGD(model.parameters(), lr = 1e-5)

In [136]:
nb_epochs = 20
for epoch in range(nb_epochs + 1):
  for batch_idx, samples in enumerate(dataloader):
    # print(batch_idx)
    # print(samples)
    x_train, y_train = samples
    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train)

    # cost로 H(x) 계산
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Batch {}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader),
        cost.item()
        ))

Epoch    0/20 Batch 1/3 Cost: 54410.015625
Epoch    0/20 Batch 2/3 Cost: 42343.062500
Epoch    0/20 Batch 3/3 Cost: 7972.339355
Epoch    1/20 Batch 1/3 Cost: 2242.608398
Epoch    1/20 Batch 2/3 Cost: 506.081055
Epoch    1/20 Batch 3/3 Cost: 111.205994
Epoch    2/20 Batch 1/3 Cost: 56.320976
Epoch    2/20 Batch 2/3 Cost: 31.966087
Epoch    2/20 Batch 3/3 Cost: 19.768400
Epoch    3/20 Batch 1/3 Cost: 5.929278
Epoch    3/20 Batch 2/3 Cost: 1.125062
Epoch    3/20 Batch 3/3 Cost: 0.277834
Epoch    4/20 Batch 1/3 Cost: 0.135496
Epoch    4/20 Batch 2/3 Cost: 5.490174
Epoch    4/20 Batch 3/3 Cost: 0.725913
Epoch    5/20 Batch 1/3 Cost: 2.366127
Epoch    5/20 Batch 2/3 Cost: 1.465055
Epoch    5/20 Batch 3/3 Cost: 0.524815
Epoch    6/20 Batch 1/3 Cost: 2.606981
Epoch    6/20 Batch 2/3 Cost: 1.272943
Epoch    6/20 Batch 3/3 Cost: 0.544203
Epoch    7/20 Batch 1/3 Cost: 0.486204
Epoch    7/20 Batch 2/3 Cost: 2.843505
Epoch    7/20 Batch 3/3 Cost: 2.238799
Epoch    8/20 Batch 1/3 Cost: 2.475793
Epoc

In [137]:
# 임의의 입력 [73, 80, 75]를 선언
new_var =  torch.FloatTensor([[73, 80, 75]]) 
# 입력한 값 [73, 80, 75]에 대해서 예측값 y를 리턴받아서 pred_y에 저장
pred_y = model(new_var) 
print("훈련 후 입력이 73, 80, 75일 때의 예측값 :", pred_y) 

훈련 후 입력이 73, 80, 75일 때의 예측값 : tensor([[152.6044]], grad_fn=<AddmmBackward0>)
